create table usuario (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    email varchar(255) not null unique,
    senha_hash varchar(255) not null,
    criado_em timestamp(6) with time zone not null,
    email_confirmado boolean default true not null
);

create table produto_monitorado (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null references usuario (id),
    loja varchar(30) not null,
    codigo_produto varchar(60) not null,
    nome varchar(500) not null,
    link varchar(1000) not null,
    imagem varchar(1000),
    preco_maximo numeric(12, 2) not null,
    preco_atual numeric(12, 2),
    preco_pix_atual numeric(12, 2),
    disponivel boolean not null,
    preco_notificado numeric(12, 2),
    ultimo_aviso_resultado varchar(30),
    ultimo_aviso_em timestamp(6) with time zone,
    criado_em timestamp(6) with time zone not null,
    ultima_verificacao timestamp(6) with time zone,
    unique (usuario_id, loja, codigo_produto)
);

create table token_email (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null references usuario (id),
    finalidade varchar(20) not null,
    hash varchar(64) not null unique,
    criado_em timestamp(6) with time zone not null,
    expira_em timestamp(6) with time zone not null
);

create index token_email_usuario on token_email (usuario_id);
